version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql_preload
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: devops_lab
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
